spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zeyh356r8r26rw66.mysql.rds.aliyuncs.com:3306/bim_yongdinghe?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: bim_yongdinghe
    password: Dwfs_ydh#*8284(002)

  redis:
    host: 192.168.1.166
    port: 6379
    timeout: 3600
    password: