server:
  port: 8181
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.66:3306/dwzc_yongdinghe?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: yongdinghe
    password: yongdinghe

  redis:
    host: 192.168.8.66
    port: 6379
    timeout: 3600
    password:
